name: "Doctests"

on:
  schedule:
    - cron: "0 */8 * * *" # Every 8 hours
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/doctests.yaml"
  merge_group:

env:
  DO_NOT_TRACK: "1"

jobs:
  static-checks:
    permissions:
      contents: "read"
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Checkout using commit hash to make "no-commit-to-branch" test pass.
          ref: ${{ github.sha }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Install Dependencies
        run: |
          # Install in system python as we're in a sandbox env
          # Install in verbose mode to see what's going on
          uv pip install --system -e '.[ci_cpu]'

      - name: Cache pre-commit
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Build documentation
        run: |
          python docs/_manage_doclinks.py copy docs/_doclinks.config
          bash docs/_docsummaries.sh
          sphinx-apidoc src/oumi --output-dir docs/api --remove-old --force --module-first --implicit-namespaces --maxdepth 2 --templatedir docs/_templates/apidoc
          sphinx-build -M html docs docs/_build -v

    # - name: Run doctests
    #   run: |
    #     make doctest
